name: Django Workflow

on:
  push:
    branches:
      - django
  workflow_dispatch:
    inputs:
      is_active:
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Install Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.13

      - name: Install Nodejs
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24

      - name: Install UV
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: 0.12.13

      - name: Prints
        run: |
          echo "Print details"
          echo "${{toJson(github)}}"
