name: Django Workflow

on:
  push:
    branches:
      - django
  workflow_dispatch:
    inputs:
      is_active:
        default: true
        type: boolean

jobs:
  django:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Install Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.13

      - name: Install Nodejs
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24

      - name: Install UV
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: 0.12.13

      - name: Check deployable
        run: |
          uv run manage.py check

      - name: Install dependencies
        run: |
          uv sync
          npm ci

      - name: Run migrations
        run: |
          uv run manage.py migrate

      - name: Check for migrations
        run: |
          uv run manage.py makemigrations --check --dry-run
          uv run manage.py showmigrations
          ls db.sqlite3

      - name: Run Django tests
        run: |
          uv run manage.py test

      - name: Collect static files
        run: uv run manage.py collectstatic --noinput

      - name: Upload Static Files
        uses: actions/upload-artifact@v7.0.1
        with:
          name: static-files
          path: staticfiles/
          retention-days: 5
