name: Initial Workflow

on:
   push:
      branches:
         - main

jobs:
   demo:
      runs-on: ubuntu-latest
      steps:
         - name: Greeting
           run: echo "Hello, World!"
              echo "My name is Yousuf Ahamad"
