name: Job Output Actions

on:
   workflow_dispatch:

jobs:
   Job1:
      runs-on: windows-latest
      outputs:
         name:
         age:
         location:
         occupation:

      steps:
         - name: Set Output
           shell: bash
           run: |
              echo "name=Yousuf Ahamad" >> $GITHUB_OUTPUT
              echo "age=25" >> $GITHUB_OUTPUT
              echo "Output variables set successfully."

         - name: Set Output 2
           run: |
              echo "location=New York" >> $GITHUB_OUTPUT
              echo "occupation=Software Engineer" >> $GITHUB_OUTPUT
              echo "Output variables set successfully."

   Job2:
      runs-on: windows-latest
      needs: Job1

      steps:
         - name: Access Output
           run: |
              echo "Name: ${{ needs.Job1.outputs.name }}"
               echo "Age: ${{ needs.Job1.outputs.age }}"
               echo "Location: ${{ needs.Job1.outputs.location }}"
               echo "Occupation: ${{ needs.Job1.outputs.occupation }}"
