name: Manual Trigger Workflow

on:
   workflow_dispatch:
      inputs:
         name:
            description: "Name of the person to greet"
            type: string
            required: true
            default: "Yousuf Ahamad"
         age:
            description: "Age of the person to greet"
            type: number
            required: false
            default: 30
         country:
            description: "Country of the person to greet"
            type: choice
            required: false
            options:
               - "India"
               - "USA"
               - "Canada"

jobs:
   demo:
      runs-on: ubuntu-latest
      steps:
         - name: Greeting
           run: echo "Manual Dispatch Triggered!, My name is ${{ inputs.name }}, I am ${{ inputs.age }} years old and I live in ${{ inputs.country }}."
