name: Manual Trigger Workflow

on:
   workflow_dispatch:
      inputs:
         name:
            description: "Name of the person to greet"
            type: string
            required: true
            default: "Yousuf Ahamad"

jobs:
   demo:
      runs-on: ubuntu-latest
      steps:
         - name: Greeting
           run: echo "Manual Dispatch Triggered!"
              echo "My name is ${{ github.event.inputs.name }}"
