name: Manual Trigger Workflow

on:
   workflow_dispatch:
      inputs:
         name:
            description: "Name of the person to greet"
            type: string
            required: true
            default: "Yousuf Ahamad"
         age:
            description: "Age of the person to greet"
            type: number
            required: false
            default: 30
         country:
            description: "Country of the person to greet"
            type: choice
            required: false
            options:
               - "India"
               - "USA"
               - "Canada"

jobs:
   Greeting:
      runs-on: ubuntu-latest
      steps:
         - name: Greeting
           run: echo "My name is ${{ inputs.name }}"
         - name: Age
           run: echo "My age is ${{ inputs.age }}"
         - name: Country
           run: echo "My country is ${{ inputs.country }}"

         - name: Greeting Message
           run: |
              echo "Hello, ${{ inputs.name }}!"
              echo "You are ${{ inputs.age }} years old."
              echo "You are from ${{ inputs.country }}."
         - name: Final Message
           run: echo "This is a manual trigger workflow. You can run it manually from the Actions tab."
