name: Manual Trigger Workflow

on:
   workflow_dispatch:

jobs:
   demo:
      runs-on: ubuntu-latest
      steps:
         - name: Greeting
           run: echo "Manual Dispatch Triggered!"
              echo "My name is Yousf"
