name: ReactJs Workflow

on:
   push:
      branches:
         - reactjs

jobs:
   ReactJsJob:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@4.2.2

         - name: Setup NodeJs
            uses: actions/setup-node@v3.9.1
            
